version: '3.9'

volumes:
    db_data: {}

services:
    back:
        container_name: game_bot_back
        ports:
            - 3000:${APP_PORT}
        networks:
            game_bot_network:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        restart: always
        depends_on:
            - db
            - cache
        links:
            - db
            - cache
    db:
        container_name: game_bot_db
        image: postgres
        restart: always
        environment:
            - POSTGRES_DB=${DB_DB}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
        networks:
            game_bot_network:
        volumes:
            - ./.docker/conf/postgres/:/docker-entrypoint-initdb.d/
            - db_data:/var/lib/postgresql/data
        ports:
            - 54330:5432

    cache:
        container_name: game_bot_cache
        image: redis:7.0.8-alpine
        restart: always
        networks:
            game_bot_network:

networks:
    game_bot_network:
